apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: service-mesh
  namespace: istio-system
spec:
  profile: default
  hub: docker.io/istio
  tag: "1.20.2"
  namespace: istio-system
  revision: prod-stable
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100.0
        zipkin:
          address: jaeger-all-in-one-collector.observability.svc.cluster.local:9411
  components:
    pilot:
      enabled: true
    ingressGateways:
    - name: istio-ingressgateway
      namespace: istio-system
      enabled: true
      k8s:
        podAnnotations:
          proxy.istio.io/config: |
            tracing:
              sampling: 100.0
              zipkin:
                address: jaeger-all-in-one-collector.observability.svc.cluster.local:9411          
      label:
        # Set a unique label for the gateway. This is required to ensure Gateways
        # can select this workload
        istio: ingressgateway
  values:
    gateways:
      istio-ingressgateway:
        # Enable gateway injection
        injectionTemplate: gateway